services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  server:
    build:
      context: ./server
    container_name: apollo-server
    restart: on-failure
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  client:
    build:
      context: ./client
    container_name: client-app
    ports:
      - "3000:80"
